package e3;

public class Network {

    //DAR DE ALTA Y DE BAJA A LOS USUARIOS DE LA RED
    //MODIFICAR LOS TEMAS QUE INTERESAN A UN DETERMINADO USUARIO
    //OBTENER LOS TEMAS QUE LE INTERESAN A UN DETERMINADO USUARIO
    //ENCONTRAR A TODOS LOS USUARIOS INTERESADOS EN UN TEMA ESPECIFICO
    //BUSCAR LOS TEMAS DE INTERÉS QUE TIENEN EN COMUN DOS USUARIOS
    //OBTENER LA LISTA DE TODOS LOS TEMAS QUE INTERESAN A LOS USUARIOS DE LA RED
    //VER LA INFORMACION DE TODOS LOS USUARIOS DE LA RED
}
